# Generated by Django 3.2.12 on 2022-03-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullCourse',
            fields=[
                ('full_course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('is_public', models.IntegerField()),
                ('view', models.PositiveIntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('started_on', models.DateField()),
                ('finished_on', models.DateField()),
            ],
            options={
                'db_table': 'full_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('info', models.TextField(blank=True, null=True)),
                ('open_time', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.SmallIntegerField()),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('label', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.CharField(blank=True, max_length=25, null=True)),
                ('average_score', models.FloatField()),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('score_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyRecommend',
            fields=[
                ('survey_recommend_id', models.BigAutoField(db_column='survey__recommend_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'survey_recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField()),
                ('profile_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishFood',
            fields=[
                ('wish_food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'wish_food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WishPlace',
            fields=[
                ('wish_place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'wish_place',
                'managed': False,
            },
        ),
    ]
