# Generated by Django 3.2.12 on 2022-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRecommend',
            fields=[
                ('main_recommend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'main_recommend',
                'managed': False,
            },
        ),
    ]
